
# This action is a simple continuous integration to run only if have a pull request to related branches.
# Actions Dependencies :
#
# - https://github.com/codecov/codecov-action used to upload code coverage.
# - https://github.com/actions/checkout used to git support features.
# - https://github.com/abatilo/actions-poetry used to manage python dependencies.

name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Running tests in python ${{matrix.python-version}} and ${{matrix.os}}

    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.python-version }}
        poetry_version: 1.0.9
        args: install

    - name: Unit tests
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.python-version }}
        poetry_version: 1.0.9
        args: run tox

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1  
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
