# This action build and publish pyppium package on pipy.
# Actions Dependencies :
#
# - https://github.com/actions/checkout used to git support features.
# - https://github.com/abatilo/actions-poetry used to manage python dependencies.


name: Build and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7
        poetry_version: 1.0.9
        args: install
        
    - name: Build and publish
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7
        poetry_version: 1.0.9
        args: publish --build -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}

        
     
